module.exports = (sequelize,DataTypes)=>{
    const Order = sequelize.define('order',
    {
        order_id:{
            type:DataTypes.STRING(150),
            allowNull:false,
            primaryKey:true
        },
        product_id:{
            type:DataTypes.STRING(150),
            allowNull:false
        },
        product_description:{
            type:DataTypes.TEXT,
            allowNull:false
        },
        product_image:{
            type:DataTypes.TEXT,
            allowNull:false
        },
        product_name:{
            type:DataTypes.STRING(150)
        },
        net_price:{
            type:DataTypes.DECIMAL(10,2)
        },
        shipping_fee:{
            type:DataTypes.DECIMAL(10,2)
        },
        payment_id:{
            type:DataTypes.STRING(200)
        },
        discount:{
            type:DataTypes.STRING(50)
        },
        option_charge:{
            type:DataTypes.STRING(50)
        },
        tracking_number:{
            type:DataTypes.STRING(200)
        },
        delivery_address:{
            type:DataTypes.STRING(200)
        },
        delivery_state:{
            type:DataTypes.STRING(200)
        },
        delivery_lga:{
            type:DataTypes.STRING(200)
        },
        delivery_town:{
            type:DataTypes.STRING(200)
        }
    },
    {
        freezeTableName:true
    }
    )
    return Order;
}